name = "htpi"
defaultTargets = ["HTPILib"]

[moreServerOptions]
linter.unusedVariables = false
linter.unusedTactic = false
pp.funBinderTypes = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.14.0"

[[lean_lib]]
name = "HTPILib"
moreLeanArgs = [
  "-Dlinter.unusedVariables=false",
  "-Dlinter.unusedTactic=false",
  "-Dpp.funBinderTypes=true",
]

[[lean_lib]]
name = "MyWork"
moreLeanArgs = [
  "-Dlinter.unusedVariables=false",
  "-Dlinter.unusedTactic=false",
  "-Dpp.funBinderTypes=true",
]
